platzigram/urls.py
"""URLs Module"""

# Django
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

#Template

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include(('posts.urls', 'posts'), namespace='posts')),
    path('users/', include(('users.urls', 'users'), namespace='users'))

] + static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

posts/urls.py
"""Posts URLs"""

# Django
from django.urls import path

# Views
from posts import views

urlpatterns = [
    path(
        route='',
        view=views.PostFeedView.as_view(),
        name='feed'
    ),
    path(
        route='posts/new/',
        view=views.CreatePostView.as_view(),
        name='create'
    ),

    path(
        route='posts/like/<int:pk>/',
        view=views.LikeView.as_view(),
        name='like'
    ),

    path(
        route='posts/<int:pk>/',
        view=views.PostDetailView.as_view(),
        name='detail'
    ),
]

users/urls.py
"""Users URLs"""

# Django
from django.urls import path
from django.views.generic import TemplateView

# View
from users import views

urlpatterns = [
    path(
        route='login/',
        view=views.LoginView.as_view(),
        name='login'
    ),
    path(
        route='logout/',
        view=views.LogoutView.as_view(),
        name='logout'
    ),
    path(
        route='signup/',
        view=views.SignupView.as_view(),
        name='signup'
    ),
    path(
        route='me/profile/',
        view=views.UpdateProfileView.as_view(),
        name='update' 
    ),

    path(
        route='follow/<str:username>/',
        view=views.FollowView.as_view(),
        name='follow'
    ),
    path(
        route='follow/let/<str:username>/',
        view=views.LetFollowView.as_view(),
        name='let_follow'
    ),

    path(
        route='<str:username>/',
        view=views.UserDetailView.as_view(),
        name='detail'
    ),
]

users/models.py
"""Users Models"""
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Profile(models.Model):
    """ Profile Model
    
    Proxy model that extends the base data with order information 
    """
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    
    website = models.URLField(max_length=500, blank=True)
    biography = models.TextField(blank=True)
    phone_number = models.CharField(max_length=20 ,blank=True)

    picture = models.ImageField(upload_to='users/pictures', blank=True, null=True)

    def followers(self):
        return Follows.objects.filter(
            followed=self
        ).count()

    def following(self):
        return Follows.objects.filter(
            follower=self
        ).count()

    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.user.username

class Follows(models.Model):
    followed = models.ForeignKey(
        Profile,
        on_delete=models.CASCADE,
        related_name='followed',
    )
    follower = models.ForeignKey(
        Profile,
        on_delete=models.CASCADE,
        related_name='follower'
    )

    class Meta:
        unique_together = ('followed', 'follower',)

    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

users/forms.py
"""Users Forms"""

# Django
from django import forms

# Models
from django.contrib.auth.models import User
from users.models import Profile

class SignUpForm(forms.Form):
    """Sign up form"""

    username = forms.CharField(min_length=3, max_length=50)
    password = forms.CharField(
        max_length=70,
        widget=forms.PasswordInput()
    )
    password_confirmation = forms.CharField(
        max_length=70,
        widget=forms.PasswordInput()
    )

    first_name = forms.CharField(min_length=2, max_length=50)
    last_name = forms.CharField(min_length=2, max_length=50)

    email = forms.CharField(
        min_length=7,
        max_length=70,
        widget=forms.EmailInput()
    )

    def clean_username(self):
        """Username must be unique"""

        username = self.cleaned_data['username']
        if User.objects.filter(username=username).exists():
            raise forms.ValidationError('Username is already in use')
        
        return username
    
    def clean(self):
        """Verify password confirmation match"""
        data = super().clean()

        password = data['password']
        password_confirmation = data['password_confirmation']

        if password != password_confirmation:
            raise forms.ValidationError('Passwords do not match')

        return data

    def save(self):
        """Create User and Profile"""
        data = self.cleaned_data
        data.pop('password_confirmation')
        
        user = User.objects.create_user(**data)
        profile = Profile(user=user)
        profile.save()

users/views.py
"""Users Views"""

# Django
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import DetailView, FormView, UpdateView, View
from django.contrib.auth import views as auth_views
from django.urls import reverse, reverse_lazy

# Forms
from users.forms import SignUpForm

# Models
from django.contrib.auth.models import User
from posts.models import Post
from users.models import Profile, Follows
from django.db.models import Count
from django.shortcuts import redirect

# Templates
TEMPLATE_LOGIN = 'users/login.html'
TEMPLATE_SIGNUP = 'users/signup.html'
TEMPLATE_UPDATE_PROFILE = 'users/update_profile.html'

# URLs
FEED = 'posts:feed'
LOGIN = 'users:login'
UPDATE_PROFILE = 'users:update'
UPDATE_DETAIL = 'users:detail'

# Constants
NAME_METHOD_POST = 'POST'
NAME_FIELD_USERNAME = 'username'
NAME_FIELD_PASSWORD = 'password'
NAME_FIELD_FIRST_NAME = 'first_name'
NAME_FIELD_LAST_NAME = 'last_name'
NAME_FIELD_EMAIL = 'email'
NAME_FIELD_WEBSITE = 'website'
NAME_FIELD_PHONE_NUMBER = 'phone_number'
NAME_FIELD_BIOGRAPHY = 'biography'
NAME_FIELD_PICTURE = 'picture'
NAME_FIELD_CONFIRMATION_PASSWORD = 'password_confirmation'

class LoginView(auth_views.LoginView):
    """Login View"""

    template_name = TEMPLATE_LOGIN


class LogoutView(LoginRequiredMixin, auth_views.LogoutView):

    template_name = LOGIN

class LetFollowView(LoginRequiredMixin, View):
    
    def get(self, request, *args, **kwargs):
        username = kwargs['username']
        u = User.objects.get(username=username)
        followed = Profile.objects.get(user=u)
        Follows.objects.get(followed=followed, follower=request.user.profile).delete()

        url = reverse(UPDATE_DETAIL, kwargs={
            'username': self.kwargs['username']
        })

        return redirect(url)

class FollowView(LoginRequiredMixin, View):
    
    def get(self, request, *args, **kwargs):
        username = kwargs['username']
        u = User.objects.get(username=username)
        followed = Profile.objects.get(user=u)
        follows = Follows(followed=followed, follower=request.user.profile)
        follows.save()
    
        url = reverse(UPDATE_DETAIL, kwargs={
            'username': self.kwargs['username']
        })

        return redirect(url)

class SignupView(FormView):

    template_name = TEMPLATE_SIGNUP
    form_class = SignUpForm
    success_url = reverse_lazy(LOGIN)

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)

class UpdateProfileView(LoginRequiredMixin, UpdateView):

    template_name = TEMPLATE_UPDATE_PROFILE
    model = Profile
    fields = ['website', 'biography', 'phone_number', 'picture']

    def get_object(self):
        return self.request.user.profile

    def get_success_url(self):
        username = self.object.user.username
        return reverse(UPDATE_DETAIL, kwargs={
            'username': username
        })

class UserDetailView(LoginRequiredMixin ,DetailView):
    template_name = 'users/detail.html'
    slug_field = 'username'
    slug_url_kwarg = 'username'
    queryset = User.objects.annotate(number_of_posts=Count('post'))
    context_object_name = 'user'

    def get_context_data(self, **kwargs):
        """Add user's posts to context"""
        context = super().get_context_data(**kwargs)
        user = self.get_object()
        context["posts"] = Post.objects.filter(user=user).order_by('-modified')
        if self.request.user != user:
            context["follows"] = Follows.objects.filter(
                follower=self.request.user.profile,
                followed=user.profile
            ).first()

        return context

templates/users/base.html
<html lang="en">
    <head>
        <meta charset="UTF-8">
        {% block head_content %}{% endblock %}

        {% load static %}
        <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/main.css' %}">
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" crossorigin="anonymous" />

    </head>
    <body>
        <div class="container h-100">
            <div class="row h-100 justify-content-center align-items-center">
                <div class="col-sm-12 col-md-5 col-lg-5 pt-2 pl-5 pr-5 pb-5" id="auth-container">
                
                <img src="{% static "img/instagram.jpg" %}" class="img-fluid rounded mx-auto d-block pb-4" style="max-width: 60%;" />

                {% block container %}{% endblock %}

                </div>
            </div>
        </div>
    </body>
</html>

templates/users/detail.html
{% extends "base.html" %}

{% block head_content %}
<title>{{ user.username }} | Platzigram</title>
{% endblock %}

{% block container %}

    <div class="container mb-5" style="margin-top: 8em;">
        <div class="row">

            <div class="col-sm-4 d-flex justify-content-center">
                <img
                    src="{{ user.profile.picture.url }}"
                    alt="@{{ user.username}}"
                    class="rounded-circle"
                    width="150px"
                />
            </div>

            <div class="col-sm-8">
                <h2 style="font-weight: 100;">
                    {{ user.username }}
                    {% if user == request.user %}
                        <a
                            href="{% url "users:update" %}"
                            class="ml-5 btn btn-sm btn-outline-info"
                        >
                            Edit profile
                        </a>
                    {% else %}
                        {% if follows.followed == user.profile %}
                            <a
                               href="{% url "users:let_follow" user.username %}"
                                class="ml-5 btn btn-sm btn-secondary"
                            >
                                Followed
                            </a>
                        {% else %}
                            <a  
                                href="{% url "users:follow" user.username %}"
                                class="ml-5 btn btn-sm btn-primary"
                            >
                                Follow
                            </a>
                        {% endif %}
                        
                    {% endif %}
                </h2>
                <div class="row mt-2" style="font-size: 1.2em">
                    <div class="col-sm-4">
                        <b>{{ user.number_of_posts }}</b> posts
                    </div>
                    <div class="col-sm-4">
                        <b>{{ user.profile.followers }}</b> followers
                    </div>
                    <div class="col-sm-4">
                        <b>{{ user.profile.following }}</b> following
                    </div>
                </div>
                <div class="row mt-4">
                    <div class="col-sm-12">
                        <p>{{ user.profile.biography }}</p>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <hr>

    <div class="container" id="user-posts">
        <div class="row mt-3">
            {% for post in posts %}
            <div class="col-sm-4 pt-5 pb-5 pr-5 pl-5 d-flex justify-content-center align-items-center">
                <a href="{% url "posts:detail" post.pk %}" class="border">
                    <img src="{{ post.photo.url }}" alt="{{ post.title }}" class="img-fluid"/>
                </a>
            </div>
            {% endfor %}
        </div>
    </div>

{% endblock %}

templates/users/login.html
{% extends 'users/base.html' %}

{% block head_content %}
<title>Sign In</title>
{% endblock %}

{% block container %}
    {% if form.errors %}
        <p class="alert alert-danger">Your username and password didn´t match. Please try again</name>
    {% endif %}
    <form method="POST" action="{% url "users:login" %}">
        {% csrf_token %}
        <div class="form-group">
            <input class="form-control" type="text" placeholder="Username" name="username" />
        </div>

        <div class="form-group">
            <input class="form-control" type="password" placeholder="Password" name="password" />
        </div>


        <button class="btn btn-primary btn-block mt-5" type="submit">Sign in!</button>
    </form>

    <p class="mt-4">Don't have an account yet? <a href="{% url "users:signup" %}">Sign up here.</a></p>
{% endblock %}

templates/users/signup.html
{% extends "users/base.html" %}

{% block head_content %}
<title>Platzigram sign up</title>
{% endblock %}

{% block container %}

    <form action="{% url 'users:signup' %}" method="POST">
        {% csrf_token %}

        {{ form.as_p }}

        <button class="btn btn-primary btn-block mt-5" type="submit">Register!</button>
    </form>

{% endblock %}

templates/users/update_profile.html
{% extends "base.html" %}
{% load static %}

{% block head_content %}
<title>@{{ request.user.username }} | Update profile</title>
{% endblock %}

{% block container %}

<div class="container">

    <div class="row justify-content-md-center">
        <div class="col-6 p-4" id="profile-box">

            <form action="{% url 'users:update' %}" method="POST" enctype="multipart/form-data">
                {% csrf_token %}

                <div class="media">
                    {% if profile.picture %}
                        <img src="{{ profile.picture.url }}" class="rounded-circle" height="50" width="50" />
                    {% else%}
                        <img src="{% static 'img/default-profile.png' %}" class="rounded-circle" height="50" width="50" />
                    {% endif %}

                    <div class="media-body">
                        <h5 class="ml-4">@{{ user.username }} | {{ user.get_full_name }}</h5>
                        <p class="ml-4"><input type="file" name="picture"></p>
                    </div>
                </div>
                {% for error in form.picture.errors %}
                    <div class="alert alert-danger">
                        <b>Picture: </b>{{ error }}
                    </div>
                {% endfor %}
                
                <hr><br>

                <div class="form-group">
                    <label>Website</label>
                    <input
                        class="form-control {% if form.website.errors %}is-invalid{% endif %}"
                        type="url"
                        name="website"
                        placeholder="Website"
                        value="{% if form.errors %}{{ form.website.value }}{% else %}{{ profile.website }}{% endif %}"
                    />
                    <div class="invalid-feedback">
                        {% for error in form.website.errors %}
                            {{ error }}
                        {% endfor %}
                    </div>
                </div>

                <div class="form-group">
                    <label>Biography</label>
                    <textarea
                        class="form-control {% if form.biography.errors %}is-invalid{% endif %}"
                        name="biography"
                    >{% if form.errors %}{{ form.biography.value }}{% else %}{{ profile.biography }}{% endif %}</textarea>
                    <div class="invalid-feedback">
                        {% for error in form.biography.errors %}
                            {{ error }}
                        {% endfor %}
                    </div>
                </div>

                <div class="form-group">
                    <label>Phone number</label>
                    <input
                        class="form-control {% if form.phone_number.errors %}is-invalid{% endif %}"
                        type="text"
                        name="phone_number"
                        placeholder="Phone number"
                        value="{% if form.errors %}{{ form.phone_number.value }}{% else %}{{ profile.phone_number }}{% endif %}"
                    />
                    <div class="invalid-feedback">
                        {% for error in form.phone_number.errors %}
                            {{ error }}
                        {% endfor %}
                    </div>
                </div>

                <button type="submit" class="btn btn-primary btn-block mt-5">Update info</button>
            </form>
        </div>
    </div>
</div>

{% endblock %}